# Use the base image that was previously created
FROM base

# Set the working directory in the container
WORKDIR /app

# Copy the application code (person_ner_server.py)
COPY person_ner_server.py /app/
COPY utils/ /app/

# Expose the port that the FastAPI app will run on
# Run the FastAPI application
CMD ["fastapi", "run", "person_ner_server.py", "--host", "0.0.0.0", "--port", "8000"]